#all information for mongo. AuthDB is NOT the database you will use for documents to go into
mongo:
  host: "127.0.0.1"
  port: 27017
  auth: false
  username: ""
  password: ""
  authDB: ""
  database: "Alchemist"

#leave blank to not use!
uri: ""

#all redis information. This is used for messaging from server to server
redis:
  host: "127.0.0.1"
  port: 6379
  username: ""
  password: ""

#server information to identify the server
server:
  id: "server1"

discord:
  enabled: false
  notificationWebhookUrl: "URL_HERE"


#theme info
defaultTheme: "MMC"

#enable and disable all modules
modules:
  ranks: true
  punishments: true
  parties: true
  friends: true
  prefixes: true
  filters: true
  chatcolors: true
  notes: true
  staffmode: true
  themeCommands: true

staffmode:
  sendWelcomeMessage: true

#for general server information to use in command messages
details:
  ip: "yourIp.xyz"
  serverWebsite: "www.yourIp.xyz"

channels:
  staffChat: "&b[SC] &7(%server%) &f%profile%&7: &b%message%"
  adminChat: "&c[AC] &7(%server%) &f%profile%&7: &c%message%"

#to incentivise players to play your server longer
freeRank:
  enabled: true
  message:
    - "change me!"
  command: "cgrant <target> Owner 10m Hello World"

# Message sent to player after granting them something
grant-message: "&aYou have been granted the &r<rank> &arank."

# Message to be sent to player when they are blacklisted from the server
blacklist-message:
  - "&cYou are blacklisted from this server."
  - "&cReason: &r<reason>"

ban-message:
    - "&cYou are banned from this server."
    - "&cReason: &r<reason>"

mute-message:
    - "&cYou are muted on this server."
    - "&cReason: &r<reason>"

warn-message:
    - "&cYou have been warned on this server."
    - "&cReason: &r<reason>"

banned-join:
  - "&cYou are currently banned from the server!"
  - "&cReason: &r<reason>"
  - "&cExpires: &r<expires>"

blacklisted-join:
    - "&cYou are currently blacklisted from the server!"
    - "&cReason: &r<reason>"
    - "&cExpires: &r<expires>"

blacklisted-join-related:
  - "&cYou are currently blacklisted from the server!"
  - "&cReason: &r<reason>"
  - "&cExpires: &r<expires>"
  - "&cIn Relation To: &r<related>"