mongo:
  host: 127.0.0.1
  port: 27017
  auth: false
  username: ''
  password: ''
  authDB: ''
  database: Alchemist
uri: ''
redis:
  host: 127.0.0.1
  port: 6379
  username: ''
  password: ''
server:
  id: server1
discord:
  punishments:
    enabled: false
    webhookLink: LINK_HERE
  grants:
    enabled: false
    webhookLink: LINK_HERE
coinshop:
  bottom_schema:
    - ' '
    - '&a&lClick Here To Purchase'
    - ' '
chat:
  slowChatMessage: '&cChat is currently slowed! Please wait &c&l<seconds> seconds'
  muteChatMessage: '&cChat is currently muted! You may not talk right now'
  rankToSendLinks:
    enabled: false
    minimum_rank: partner
autobroadcast:
  enabled: true
  interval: 60
  messages:
    alchemist:
      - ' '
      - "&8[&5&lGitHub&8] &8\xc2\xbb &dAlchemist &f is available on &5GitHub!"
      - '&fHead to &7github.com/98ping/Alchemist'
      - ' '
    mcmarket:
      - ' '
      - "&8[&9&lBuiltByBit&8] &8\xc2\xbb &bAlchemist &f is available on &9BuiltByBit!"
      - '&fHead to https://builtbybit.com/members/objectify.178715/'
      - ' '
defaultTheme: custom
profiles:
  load:
    sendMessage: true
    message: "&b✓ &aYour profile has been successfully loaded"
grants:
  durationMenuSize: 27
  reasonMenuSize: 27
modules:
  ranks: true
  punishments: true
  parties: true
  friends: true
  prefixes: true
  coins: true
  filters: true
  queue: false
  chatcolors: true
  notes: true
  staffmode: true
  chat: true
  vouchers: true
  essentials: true
  themeCommands: true
staffmode:
  sendWelcomeMessage: true
  autoEquipOnJoin: false
details:
  ip: yourIp.xyz
  serverWebsite: www.yourIp.xyz
channels:
  staffChat: '&b[SC] &7(%server%) &f%profile%&7: &b%message%'
  adminChat: '&c[AC] &7(%server%) &f%profile%&7: &c%message%'
freeRank:
  enabled: true
  message:
    - change me!
  command: cgrant <target> Default 10m Hello World
grant-message: '&eYou have been granted the &r<rank> &erank for a duration of &6<duration>.'
consoleColor: '&c&l'
message:
  message_format_from: '&7(From &r<from> &7to &cme&7) &f<message>'
  message_format_to: '&7(From &cme &7to &r<from>&7) &f<message>'
  staff_message_format_to: '&7(From &3&oStaff &7to &r<from>&7) &f<message>'
  staff_message_format_from: '&7(From &3&oStaff &7to &cme&7) &f<message>'
  sound: LEVEL_UP
queue-message:
  - ' '
  - '&dYou are position &e#<pos> &din the &e<queue_name> &dqueue,'
  - '&bYour &f<colored_rank> &brank has placed you in front of <front> players.'
  - '&6To leave the queue, use /leavequeue'
  - ' '
blacklist-message:
  - '&cYou are blacklisted from this server.'
  - '&cReason: &r<issued_reason>'
ban-message:
  - '&cYou are banned from this server.'
  - '&cReason: &r<issued_reason>'
mute-message:
  - '&cYou are muted on this server.'
  - '&cReason: &r<issued_reason>'
muted-chat:
  - '&cYou are muted on this server.'
  - '&cReason: &r<issued_reason>'
kick-message:
  - '&cYou were kicked from this server.'
  - '&cReason: &r<issued_reason>'
warn-message:
  - '&cYou have been warned on this server.'
  - '&cReason: &r<issued_reason>'
banned-join:
  - '&cYou are currently banned from the server!'
  - '&cReason: &r<issued_reason>'
  - '&cExpires: &r<expires>'
blacklisted-join:
  - '&cYou are currently blacklisted from the server!'
  - '&cReason: &r<issued_reason>'
  - '&cExpires: &r<expires>'
blacklisted-join-related:
  - '&cYou are currently blacklisted from the server!'
  - '&cReason: &r<issued_reason>'
  - '&cExpires: &r<expires>'
  - '&cIn Relation To: &r<related>'
custom-theme:
  grants:
    active-item:
      name: '&a&l(Active)&r &a<issued_date>'
      material: WOOL
      data: 5
    inactive-item:
      name: '&c&l(Inactive)&r &c<issued_date>'
      material: WOOL
      data: 14
    expired-item:
      name: '&6&l(Expired)&r &6<issued_date>'
      material: WOOL
      data: 1
    lore:
      scope-display: '&7- &a<scope>'
      active:
        permanent:
          - '&6&m-------------------------------------'
          - '&eTarget: &f<target>'
          - '&eRank: &f<rank>'
          - '&eDuration: &fForever'
          - '&6&m-------------------------------------'
          - '&eScopes:'
          - <scopes>
          - '&6&m-------------------------------------'
          - '&eIssued By: &f<issued_by>'
          - '&eIssued Reason: &f<issued_reason>'
          - '&6&m-------------------------------------'
          - '&aRight-Click to remove this grant from &f<target>&a.'
          - '&aLeft-Click to edit the scopes of this grant'
          - '&6&m-------------------------------------'
        temporary:
          - '                &a<expires_at>'
          - '&6&m-------------------------------------'
          - '&eTarget: &f<target>'
          - '&eRank: &f<rank>'
          - '&eDuration: &f<duration>'
          - '&6&m-------------------------------------'
          - '&eScopes:'
          - <scopes>
          - '&6&m-------------------------------------'
          - '&eIssued By: &f<issued_by>'
          - '&eIssued Reason: &f<issued_reason>'
          - '&6&m-------------------------------------'
          - '&aRight-Click to remove this grant from &f<target>&a.'
          - '&aLeft-Click to edit the scopes of this grant'
          - '&6&m-------------------------------------'
      inactive:
        permanent:
          - '                &c<removal_date>'
          - '&6&m-------------------------------------'
          - '&eTarget: &f<target>'
          - '&eRank: &f<rank>'
          - '&eDuration: &fForever'
          - '&6&m-------------------------------------'
          - '&eScopes:'
          - <scopes>
          - '&6&m-------------------------------------'
          - '&eIssued By: &f<issued_by>'
          - '&eIssued Reason: &f<issued_reason>'
          - '&6&m-------------------------------------'
          - '&eRemoved By: &f<removed_by>'
          - '&eRemoval Reason: &f<removal_reason>'
          - '&6&m-------------------------------------'
          - '&aRight-Click to remove this grant from &f<target>&a.'
          - '&aLeft-Click to edit the scopes of this grant'
          - '&6&m-------------------------------------'
        temporary:
          - '                &c<removal_date>'
          - '&6&m-------------------------------------'
          - '&eTarget: &f<target>'
          - '&eRank: &f<rank>'
          - '&eDuration: &f<duration>'
          - '&6&m-------------------------------------'
          - '&eScopes:'
          - <scopes>
          - '&6&m-------------------------------------'
          - '&eIssued By: &f<issued_by>'
          - '&eIssued Reason: &f<issued_reason>'
          - '&6&m-------------------------------------'
          - '&eRemoved By: &f<removed_by>'
          - '&eRemoval Reason: &f<removal_reason>'
          - '&6&m-------------------------------------'
          - '&aRight-Click to remove this grant from &f<target>&a.'
          - '&aLeft-Click to edit the scopes of this grant'
          - '&6&m-------------------------------------'
      expired:
        permanent:
          - '                &6<removal_date>'
          - '&6&m-------------------------------------'
          - '&eTarget: &f<target>'
          - '&eRank: &f<rank>'
          - '&eDuration: &fForever'
          - '&6&m-------------------------------------'
          - '&eScopes:'
          - <scopes>
          - '&6&m-------------------------------------'
          - '&eIssued By: &f<issued_by>'
          - '&eIssued Reason: &f<issued_reason>'
          - '&6&m-------------------------------------'
          - '&aRight-Click to remove this grant from &f<target>&a.'
          - '&aLeft-Click to edit the scopes of this grant'
          - '&6&m-------------------------------------'
        temporary:
          - '                &6<removal_date>'
          - '&6&m-------------------------------------'
          - '&eTarget: &f<target>'
          - '&eRank: &f<rank>'
          - '&eDuration: &f<duration>'
          - '&6&m-------------------------------------'
          - '&eScopes:'
          - <scopes>
          - '&6&m-------------------------------------'
          - '&eIssued By: &f<issued_by>'
          - '&eIssued Reason: &f<issued_reason>'
          - '&6&m-------------------------------------'
          - '&aRight-Click to remove this grant from &f<target>&a.'
          - '&aLeft-Click to edit the scopes of this grant'
          - '&6&m-------------------------------------'
